jobs:
  build:
    machine:
      image: suse-sles-15-sp3-v20211219-hvm-ssd-x86_64
    steps:
      - checkout
      #- run:
      #    name: updating apt-get
      #    command: sudo apt-get update
      #- run:
      #    name: installing awscli
      #    command: sudo apt-get install awscli
      #- run:
      #    name: transfering current folder to ec2 instance
      #    command: scp -r ./dockerfile_folder ec2-user@ec2-13-235-13-153.ap-south-1.compute.amazonaws.com:/home/ec2-user/docker_images/custom_sles_image
      - run:
          name: starting containerbuild-regionsrv
          command: sudo systemctl start containerbuild-regionsrv
      - run:
          name: buidling image in ec2 instance
          command: sudo docker build -t custom_sles_image2 --network host ./dockerfile_folder/

workflows:
  version: 2
  workflow_name:
    jobs:
      - build
