jobs:
  build:
    docker:
      - image: 657273346644.dkr.ecr.us-east-1.amazonaws.com/hpe-hcss/containerize:v1.2.2

    steps:
      - checkout
      #- run:
      #    name: installing awscli
      #    command: sudo apt-get install awscli
      #- run:
      #    name: transfering current folder to ec2 instance
      #    command: scp -r ./dockerfile_folder ec2-user@ec2-13-235-13-153.ap-south-1.compute.amazonaws.com:/home/ec2-user/docker_images/custom_sles_image
      - setup_remote_docker
      #- run:
      #    name: starting containerbuild-regionsrv
      #    command: systemctl start containerbuild-regionsrv
      - run:
          name: buidling image in docker instance
          command: docker build -t custom_sles_image ./dockerfile_folder/
      - run:
          name: aws registry login
          command: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 731786372306.dkr.ecr.ap-south-1.amazonaws.com
      - run:
          name: tag the image
          command: docker tag custom_sles_image:latest 731786372306.dkr.ecr.ap-south-1.amazonaws.com/custom_sles_image:latest
      - run:
          name: push the image to ecr
          command: docker push 731786372306.dkr.ecr.ap-south-1.amazonaws.com/custom_sles_image:latest
workflows:
  version: 2
  workflow_name:
    jobs:
      - build
